{% set name = "simple-websocket" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple-websocket-{{ version }}.tar.gz
  sha256: 82c0b0b1006d5490f09ff66392394d90dd758285635edad241e093e9a8abd3eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - wsproto

test:
  imports:
    - simple_websocket
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/miguelgrinberg/simple-websocket
  summary: Simple WebSocket server and client for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - woutdenolf
